# Numpy-2

In [2]:
import numpy as np

In [3]:
np.random.randint(-10,-1,4)   #generates negative random 4 values  

array([-6, -5, -9, -9], dtype=int32)

In [4]:
np.random.randint(10,50,(5,5))  #creates 5x5 matrix of random values between 10 to 50-1

array([[15, 17, 26, 49, 23],
       [41, 17, 38, 47, 36],
       [35, 22, 11, 33, 38],
       [15, 39, 35, 40, 42],
       [28, 24, 38, 46, 37]], dtype=int32)

In [6]:
a= np.random.randint(4,20,(3,5)) 
a

array([[ 4,  9,  8, 12,  6],
       [14,  9,  8, 12, 17],
       [ 6, 13, 13, 17,  5]], dtype=int32)

In [7]:
len(a)    #length function in numpy will always give the the length of the "NO. OF ROWS IN THE MATRIX"

3

In [8]:
a.shape    #shape function will tell the dimension of the matrix is.

(3, 5)

# SLICING IN NUMPY

In [9]:
a[:]    #displays whole matrix

array([[ 4,  9,  8, 12,  6],
       [14,  9,  8, 12, 17],
       [ 6, 13, 13, 17,  5]], dtype=int32)

In [10]:
a[0] #displays 0th Row

array([ 4,  9,  8, 12,  6], dtype=int32)

In [11]:
a[1]    #displays 1st Row

array([14,  9,  8, 12, 17], dtype=int32)

In [12]:
a[2]  #displays 2nd Row

array([ 6, 13, 13, 17,  5], dtype=int32)

In [13]:
x=np.random.randint(10,50,(10,10))
x

array([[34, 28, 30, 44, 23, 29, 37, 11, 42, 39],
       [20, 20, 49, 49, 40, 20, 32, 48, 10, 26],
       [29, 19, 30, 11, 18, 26, 24, 22, 39, 11],
       [11, 45, 14, 19, 43, 24, 38, 25, 12, 49],
       [32, 38, 30, 15, 31, 35, 23, 34, 27, 20],
       [20, 25, 40, 41, 49, 12, 17, 45, 25, 21],
       [34, 45, 34, 42, 16, 12, 14, 11, 30, 19],
       [15, 33, 28, 20, 32, 12, 36, 45, 10, 31],
       [11, 32, 15, 22, 26, 35, 46, 48, 36, 24],
       [14, 44, 38, 40, 35, 41, 10, 15, 28, 25]], dtype=int32)

In [14]:
x[3:8]   #displays the rows from 3rd ---> 8-1=7th 

array([[11, 45, 14, 19, 43, 24, 38, 25, 12, 49],
       [32, 38, 30, 15, 31, 35, 23, 34, 27, 20],
       [20, 25, 40, 41, 49, 12, 17, 45, 25, 21],
       [34, 45, 34, 42, 16, 12, 14, 11, 30, 19],
       [15, 33, 28, 20, 32, 12, 36, 45, 10, 31]], dtype=int32)

In [15]:
print(x[3,8])   #if we give "," in between then it will give the specific position value at 3rd row and 8th column

12


In [16]:
print(x[-5])

[20 25 40 41 49 12 17 45 25 21]


In [17]:
print(x[-5,-3])

45


In [18]:
print(x[::3])   #+3 steps

[[34 28 30 44 23 29 37 11 42 39]
 [11 45 14 19 43 24 38 25 12 49]
 [34 45 34 42 16 12 14 11 30 19]
 [14 44 38 40 35 41 10 15 28 25]]


In [20]:
x[:,3]    # prints the specific column

array([44, 49, 11, 19, 15, 41, 42, 20, 22, 40], dtype=int32)

In [21]:
print(x[2])    #prints the 2nd row
print(x[:,5])    #prints the 5th column       

[29 19 30 11 18 26 24 22 39 11]
[29 20 26 24 35 12 12 12 35 41]


In [22]:
print(x)

[[34 28 30 44 23 29 37 11 42 39]
 [20 20 49 49 40 20 32 48 10 26]
 [29 19 30 11 18 26 24 22 39 11]
 [11 45 14 19 43 24 38 25 12 49]
 [32 38 30 15 31 35 23 34 27 20]
 [20 25 40 41 49 12 17 45 25 21]
 [34 45 34 42 16 12 14 11 30 19]
 [15 33 28 20 32 12 36 45 10 31]
 [11 32 15 22 26 35 46 48 36 24]
 [14 44 38 40 35 41 10 15 28 25]]


In [23]:
print(x[2:5,4:7])    #this will print the values between 2-->4th row and 4-->6th column

[[18 26 24]
 [43 24 38]
 [31 35 23]]


In [24]:
np.arange(10,19)

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [31]:
np.arange(10,22).reshape(3,4)   #this is convert the range of the values into 3x4 matrix

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# NUMPY MASKING OR FILTER

In [32]:
z= np.arange(0,100).reshape(10,10)
z

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [33]:
z < 50    #this will check the condition is the value less than 50 if yes then TRUE else FALSE

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [34]:
z[z<50]    #list of values which are less than 50, applied both masking and filtering 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [35]:
z[z!=50]   #prints the values which is not equal to 50 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])