# ARRAY CREATION FUNCTIONS

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])  #creates an array from the list 
print("ARRAY IS:",a)


ARRAY IS: [1 2 3]


In [4]:
b=np.arange(0,10,2)   #makes a range of value from 0 to 9 with forward step of +2
print("Values are:",b)


Values are: [0 2 4 6 8]


In [7]:
c=np.zeros((2,3))
print("VALUES ARE:\n",c)


VALUES ARE:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
d=np.ones((2,3),dtype=int)
print("VALUES ARE:\n",d)


VALUES ARE:
 [[1 1 1]
 [1 1 1]]


In [12]:
e=np.eye(4)   #creates an identity matrix of 4x4
print("IDENTITY MATRIX IS:\n",e)


IDENTITY MATRIX IS:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
 np.identity(4)    #creates an identity matrix of 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# ARRAY MANUPULATION FUNCTIONS

In [15]:
x=np.array([1,2,3])
re=np.reshape(x,(3,1))    #conversion from rows to column
print(re)

[[1]
 [2]
 [3]]


In [17]:
y=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
flat=np.ravel(y)    #flatten the multiple array into single dimension  CONVERTS INTO 1-D
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [18]:
z=np.array([[1,2],[3,4]])
tr=np.transpose(z)    #converts into transpose
print(tr)

[[1 3]
 [2 4]]


In [23]:
a1=np.array([1,2])
a2=np.array([3,4])
stacking=np.stack([a1,a2])     #uses STACK to vertical stack bydefualt
print(stacking)

[[1 2]
 [3 4]]


In [24]:
b1=np.array([1,2])
b2=np.array([3,4])
stacking=np.hstack([b1,b2])     #uses STACK to horizontal stack
print(stacking)

[1 2 3 4]


# MATHEMATICAL FUNCTIONS

In [26]:
p=np.array([1,2,3,4])
g=np.add(p,4)    #add value=+4 to all the elements of the array
print(g)

[5 6 7 8]


In [27]:
x=np.power(g,2)    #squaring of the elements of the array
print(x)

[25 36 49 64]


In [29]:
sr=np.sqrt(x)    #srquare root of the elemnets 
print(sr)

[5. 6. 7. 8.]


In [30]:
a=np.array([1,2,3])
b=np.array([1,2,3])
dp=np.dot(a,b)     #performs dot product of the arrays
print(dp)


14


# STATISTICAL FUNCTIONS

In [31]:
s=np.array([1,2,3,4])
m=np.mean(s)    #performs mean to the array element
print(m)

2.5


In [32]:
std=np.std(s)   #performs standard deviation to the array
print(std)

1.118033988749895


In [35]:
print(np.min(s))   #performs min

1


In [34]:
print(np.max(s))    #performs max

4


In [36]:
print(np.var(s))     #performs variance

1.25


# RANDOM SAMPLING FUNCTIONS

In [40]:
rv=np.random.rand(3)    #bydefault its float value  
print(rv)

[0.43758721 0.891773   0.96366276]


In [42]:
np.random.seed(0)   #when we run again and again the random value code it will generate new new values BUT WHEN WE GIVE SEED=0 THEN WHEN WE RUN AGAIN AND AGAIN WE GET THE SAME VALUE
rv=np.random.rand(3)
print(rv)

[0.5488135  0.71518937 0.60276338]


In [54]:
ri= np.random.randint(0,10,size=5)
print(ri)

[5 4 4 5 7]


In [57]:
np.random.seed(0)
ri= np.random.randint(0,10,size=5)
print(ri)

[5 0 3 3 7]
