# NUMPY-1

In [2]:
import numpy as np     #importing the numpy module

In [4]:
np.__version__     #  checking the version of the numpy

'2.3.5'

In [1]:
my_list=[0,1,2,3,4,5]        #creating an 1-D list to convert into array
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr= np.array(my_list)   #conversion from list to array

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)      #nd=1-D array

numpy.ndarray

In [10]:
np.arange(10)    #same as range datatype in python basics

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(10,20)    #start and end-1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(10,20,3)    #start and end-1 with steps=+3

array([10, 13, 16, 19])

In [14]:
np.zeros(5)    # bydefault the parameter is this zeros(shape, dtype=float, order='C', *, like=None) & 1-D array

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(5, dtype=int)  #changing the type from float to int   & 1-D array

array([0, 0, 0, 0, 0])

In [18]:
np.zeros((4,2))    # 2-D array and float datatype bydefault

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.zeros((4,2), dtype=int)  #2-D array and int datatype  or 2x2 matrix

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [20]:
np.zeros((5,10), dtype=int)    # 5x10 matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
np.ones(5)   #creates a array of only 1's value & its a 1-D value

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((3,5), dtype=int)   # 3x5 matrix with int datatype

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
np.random.rand(4)   #generates random values and when we run again and again the values get shuffled

array([0.92985481, 0.40966992, 0.12128117, 0.90357429])

In [25]:
np.random.randint(0,10)  #its returns any random value between start to end-1 any random value

8